### PR TITLE
Working branch

### PR DESCRIPTION
**Pull request by Haywhizzz**
In this project

- I used bootstrap for the project

- I made sure it was responsive on small, medium and large screens

- I made a clone of the news week website

### CODE REVIEW

**Comment by bertil291utn** [comment]
**Status:** Invalid 🔴  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### But before to start reviewing please check you linter errors.

image


<hr>
Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle:   :stop_sign: 
### HELLO @Haywhizzz  AM PETER ROBERT A TSE AND  I HAVE REVIEWED YOUR PROJECT. IT SEEMS YOUR PROJECT IS NOT YET COMPLETE KINDLY MAKE THE FOLLOWING CHANGES.

- [x] Your live view in your readme file is not reflecting your actual work kindly remember you should make sure you submit your own work for review.

- [x] The containers on your webpage are not well aligned and styled also remember this is a project where you have to make your site responsive you should do that.

- [x] Kindly before you submit any project make sure it's complete.

### If you have any question concerning the review kindly reach me on slack @peterrobert

### HAPPY CODING :computer:

**Review by kitpao — CHANGES_REQUESTED** [review]
# 👋 Hello @Haywhizzz ,

Your page looks good and close to the original 🥇 you also took care of the linters and made a good advance

However, it still is missing some details in the responsive breakpoints and in the good practices, please read the following and the requirements below this note ⬇️

- [x] **[MANDATORY]** Add all not related files ( the node_module folder) to the .gitignore so it won't be commited to your repo, this will also help you because in this way, you don't have to correct the linters in all the files from that directory
image

- [x] **[MANDATORY]** In **desktop** and in **tablet** breakpoints, kindly align this part for all your sections:
image

- [x] **[MANDATORY]** Your page in **desktop** and in **tablet** versions is missing the Newsletter and subscribe sections near the footer, please add it:
image

- [x] **[MANDATORY]** In **mobile** notice that the height of your navbar is considerably bigger, and also the sections in the original page change the order of the section with responsive behavior, please kindly fix it:
image

### ♻️ Status: Your project requires some additional changes ♻️

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Comment by Haywhizzz** [comment]
I fixed the ordering issue, the alignment issue and made the newsletter and subscribe section appear on medium and large screens

**Review by expjazz — CHANGES_REQUESTED** [review]
## Status: Changes required :recycle: 

#### Hello @Haywhizzz. You did a marvelous job on this project :clap: 

#### The page looks really good and you showed a lot of confidence in the use of the bootstrap classes.

However, since you added the subscribe and newsletter sections, now a new problem came up:

- [x]  The image of the newsletter is out of frame, overflowing outside the element. The height is also different (check-in all screen sizes)

| Yours | Original |
|:---:|:---:|
| image | image |

- [x] Now that you fixed the navbar in the mobile screen, a new problem came up. The hamburger menu should not go to a new row.

| Yours | Original |
|:---:|:---:|
| image | image |

- [optional] In the mobile screen size, these sections on the screenshot below should have the background white (you did a great job with the background color, the problem lies only in this section).

| Yours | Original |
|:---:|:---:|
| image | image |

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Comment by Haywhizzz** [comment]
I fixed the navbar and the overflowing element issue

**Review by kitpao — CHANGES_REQUESTED** [review]
# 👋 Hi again @Haywhizzz ,

You did a good job with the previous fixes 👍, however, when you made them, they triggerered new details in your design: 
- [x] In **tablet** mode, you lost your margin in some sections (see image)
- [x] In **tablet** mode you have a horizontal scroll, this should not happen when it is responsive since it should adapt to the user's screen size (maybe there is a big element in your page, you can also use `overflow-x: hidden` )
image

- [x] **OPTIONAL**: In **mobile** your Newsweek logo at the top is pretty small, you can try by changing the value in your image of `width:50%`

You are almost done 🔨
### ♻️ Status: Your project requires some additional changes ♻️

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Comment by Haywhizzz** [comment]
fixed all errors indicated on the review

**Comment by bertil291utn** [comment]
**Status:** Changes requested 🟠  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below: 

- [ ] Please add a more meaningful pull request message. Follow [these guidelines](https://microverse.pathwright.com/auth/sign-in/?next=/library/fast-track-curriculum/69047/path/step/66243642/) and edit your pull request comment box

image

- [ ] Add margin for small and medium screens approach

image

**Small screen**

- [ ]  My turn and culture and travel section have twice, shouldn't be there before **in the magazine section**

image

- [ ] You're missing the first article **in the magazine** section. Change for all size screens

|                       ACTUAL WEB PAGE                        |                            YOURS                             |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
| image | image |

- [ ] **Footer** should be an image or SVG, not a text.

image

**Medium screen**

- [ ] **Navbar.**- Should be **LOGIN** text instead profile icon

image



 **Large screen**

- [ ] This margin shouldn't be there. Check again the [original page](https://www.newsweek.com/) with large size screen

image

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Comment by Haywhizzz** [comment]
I started the project last week and haven't really refreshed the page again, so some of the images/contents on the page have changed, but I worked with what I had loaded on my browser

**Review by kitpao — CHANGES_REQUESTED** [review]
# 👋 Hello @Haywhizzz ,

You did well implementing the changes my previous colleague asked you 😌 you are almost there, and only missing some margin issues, they are the following 🔨:

- [x] Be careful with your newsletter's and footer's margins in **tablet**
image

- [x] Same issue with margin but only for footer in **mobile**
image

- [x] Footer's margin also looks moved in **desktop**
image

### ♻️ Status: Your project requires some additional changes ♻️

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Great job so far team, thank you for making the required changes by the previous TSE's, but in order to make your project approved you need to make one final change.

- [x] remove the node_modules folder from your repository

### Please make the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you feel stuck or have any questions don't hesitate to contact me on slack_

**Comment by Haywhizzz** [comment]
I made the final change which is removing the node-modules folder from my repo

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle: :stop_sign: 
### HEY @Haywhizzz  VERY NICE WORK I CAN SEE THAT THE PROJECT IS PROGRESSING ON WELL GOOD WORK :clap: :clap: 

### HOWEVER THERE ARE A FEW REMAINING THINGS THAT HAVE PREVENTED ME FROM APPROVING THIS PROJECT. KINDLY IMPROVE ON THE FOLLOWING

- [x] Kindly you need to fix the menu bar. It doesn't look like the original. Kindly fix it
### YOURS
menu
### ORIGINAL
menu original

- [ ] Also there is a misalignment vertically between those two sections:arrow_down: Kindly fix
### YOURS
margin
### ORIGINAL
margin original

### once you fix those kindly submit your project for another review

### HAPPY CODING :computer:

**Review by kitpao — APPROVED** [review]
# 👋 Hello @Haywhizzz 

🌟 Congratulations!!! You did all changes and your project is looking awesome! 💯 Be proud of yourself for your hard-work 😎  

### 👏 Status: Your project has been approved 👏
### 🚀 You may merge to master and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Pull request closed without merging**
